name: Gradle Publishing Workflow

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'build.gradle'
      - 'src/**'

jobs:
  publish-with-gradle:
    name: Publish with Gradle on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        distribution: [temurin, zulu]
        java-version: [11, 17]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for better reliability
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
      
      # Create Gradle wrapper explicitly
      - name: Create Gradle Wrapper
        shell: bash
        run: |
          mkdir -p gradle/wrapper
          curl -o gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradle-wrapper.jar
          
          cat > gradle/wrapper/gradle-wrapper.properties << 'EOF'
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip
          networkTimeout=10000
          validateDistributionUrl=true
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          EOF
          
          cat > gradlew << 'EOF'
          #!/bin/sh
          exec java -classpath gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain "$@"
          EOF
          
          cat > gradlew.bat << 'EOF'
          @echo off
          java -classpath gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain %*
          EOF
          
          # Explicitly set permissions on all platforms
          chmod +x gradlew

      - name: Verify gradlew permissions
        shell: bash
        run: |
          ls -la gradlew || echo "No gradlew file"
          
          # Make executable again just to be sure
          if [ -f "gradlew" ]; then
            chmod +x gradlew
          fi
      
      # Use platform-specific commands
      - name: Build with Gradle (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: gradlew.bat build
      
      - name: Build with Gradle (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: ./gradlew build
      
      - name: Publish to GitHub Packages (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: gradlew.bat publish
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ github.token }}
          
      - name: Publish to GitHub Packages (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ github.token }}
      
      - name: Report status
        run: |
          echo "Successfully published with Gradle"
          echo "Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-07-20 10:57:39"
          echo "Current User's Login: mahabaleshwars"
