name: Maven Publishing to Central Repository

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [17]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Apache Maven Central
      uses: aparnajyothi-y/setup-java@toolversions-regex-update
      with:
        distribution: 'jetbrains'
        java-version: ${{ matrix.java-version }}
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MY_GPG_PASSPHRASE
    
    - name: Display Java version
      run: java -version
    
    - name: Build with Maven
      run: mvn -B clean package
      
    - name: Verify POM and settings
      run: |
        echo "Checking effective POM..."
        mvn help:effective-pom
        echo "Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-07-23 06:07:54"
        echo "Current User's Login: mahabaleshwars"

    - name: Publish to Apache Maven Central
      run: mvn -P release --batch-mode deploy -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MY_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        
    - name: Verify deployment status
      if: success()
      run: |
        echo "Deployment completed successfully"
        echo "Check Sonatype Repository Manager for your artifacts"
        echo "Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-07-23 06:07:54"
        echo "Current User's Login: mahabaleshwars"
