name: Maven Publishing to Central Repository

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-to-maven-central:
    name: Publish to Sonatype Central with ${{ matrix.distribution }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [adopt, corretto, dragonwell, sapmachine, graalvm, jetbrains, temurin, zulu, liberica, semeru]
        java-version: [21]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      
      - name: Create project structure
        run: mkdir -p src/main/java/com/example/demo
      
      - name: Create Java class
        run: |
          cat > src/main/java/com/example/demo/DemoApp.java << 'EOF'
          package com.example.demo;
          
          public class DemoApp {
              public String getMessage() {
                  return "Hello from Sonatype Central Publisher!";
              }
              
              public static void main(String[] args) {
                  System.out.println(new DemoApp().getMessage());
                  System.out.println("Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-07-21 02:34:54");
                  System.out.println("Current User's Login: mahabaleshwars");
              }
          }
          EOF
      
      - name: Create pom.xml for Sonatype Central
        run: |
          cat > pom.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
              <modelVersion>4.0.0</modelVersion>
              
              <groupId>io.github.mahabaleshwars</groupId>
              <artifactId>maven-central-demo</artifactId>
              <version>1.0.0-SNAPSHOT</version>
              <packaging>jar</packaging>
              
              <name>Sonatype Central Demo</name>
              <description>Demo project for publishing to Sonatype Central</description>
              <url>https://github.com/mahabaleshwars/Java-PR-Test</url>
              
              <licenses>
                  <license>
                      <name>MIT License</name>
                      <url>http://www.opensource.org/licenses/mit-license.php</url>
                  </license>
              </licenses>
              
              <developers>
                  <developer>
                      <id>mahabaleshwars</id>
                      <name>Developer Name</name>
                      <email>developer@example.com</email>
                      <organization>Example Organization</organization>
                      <organizationUrl>https://www.example.com</organizationUrl>
                  </developer>
              </developers>
              
              <scm>
                  <connection>scm:git:git://github.com/mahabaleshwars/Java-PR-Test.git</connection>
                  <developerConnection>scm:git:ssh://github.com:mahabaleshwars/Java-PR-Test.git</developerConnection>
                  <url>https://github.com/mahabaleshwars/Java-PR-Test/tree/main</url>
              </scm>
              
              <properties>
                  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                  <maven.compiler.source>11</maven.compiler.source>
                  <maven.compiler.target>11</maven.compiler.target>
              </properties>
              
              <!-- Updated repositories for Sonatype Central -->
              <distributionManagement>
                  <snapshotRepository>
                      <id>central</id>
                      <url>https://central.sonatype.com/content/repositories/snapshots</url>
                  </snapshotRepository>
                  <repository>
                      <id>central</id>
                      <url>https://central.sonatype.com/content/repositories/releases</url>
                  </repository>
              </distributionManagement>
              
              <build>
                  <plugins>
                      <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-compiler-plugin</artifactId>
                          <version>3.11.0</version>
                      </plugin>
                      <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-source-plugin</artifactId>
                          <version>3.3.0</version>
                          <executions>
                              <execution>
                                  <id>attach-sources</id>
                                  <goals>
                                      <goal>jar-no-fork</goal>
                                  </goals>
                              </execution>
                          </executions>
                      </plugin>
                      <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-javadoc-plugin</artifactId>
                          <version>3.5.0</version>
                          <executions>
                              <execution>
                                  <id>attach-javadocs</id>
                                  <goals>
                                      <goal>jar</goal>
                                  </goals>
                              </execution>
                          </executions>
                      </plugin>
                      <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-gpg-plugin</artifactId>
                          <version>3.1.0</version>
                          <executions>
                              <execution>
                                  <id>sign-artifacts</id>
                                  <phase>verify</phase>
                                  <goals>
                                      <goal>sign</goal>
                                  </goals>
                                  <configuration>
                                      <gpgArguments>
                                          <arg>--pinentry-mode</arg>
                                          <arg>loopback</arg>
                                      </gpgArguments>
                                  </configuration>
                              </execution>
                          </executions>
                      </plugin>
                      <!-- Replaced nexus-staging-maven-plugin with maven-deploy-plugin configured for Central -->
                      <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-deploy-plugin</artifactId>
                          <version>3.1.1</version>
                          <configuration>
                              <deployAtEnd>true</deployAtEnd>
                          </configuration>
                      </plugin>
                  </plugins>
              </build>
          </project>
          EOF
      
      - name: Create Maven settings for Sonatype Central
        run: |
          cat > settings.xml << EOF
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>\${env.MAVEN_USERNAME}</username>
                <password>\${env.MAVEN_PASSWORD}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>gpg</id>
                <properties>
                  <gpg.executable>gpg</gpg.executable>
                  <gpg.passphrase>\${env.MAVEN_GPG_PASSPHRASE}</gpg.passphrase>
                </properties>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>gpg</activeProfile>
            </activeProfiles>
          </settings>
          EOF
      
      - name: Build with Maven
        run: mvn -B package
      
      - name: Deploy to Sonatype Central (Dry Run)
        run: mvn -B help:evaluate -Dexpression=project.version -s settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME || 'dummy-username' }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD || 'dummy-password' }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE || 'dummy-passphrase' }}
      
      - name: Verify deployment configuration
        run: |
          mvn -B help:effective-pom -s settings.xml
          mvn -B deploy -DaltDeploymentRepository=local::default::file:./target/deploy-repo -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME || 'dummy-username' }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD || 'dummy-password' }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE || 'dummy-passphrase' }}
          
      - name: Report status
        run: |
          echo "Maven Publishing to Sonatype Central workflow"
          echo "Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-07-21 02:34:54"
          echo "Current User's Login: mahabaleshwars"
