name: Maven Publishing to Central Repository

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-to-maven-central:
    name: Publish to Maven Central with ${{ matrix.distribution }} JDK ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [temurin]
        java-version: [11]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
          server-id: maven
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Publish to Apache Maven Central
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      
      - name: Report status
        run: |
          echo "Successfully published to Maven Central"
          echo "Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-07-20 10:25:51"
          echo "Current User's Login: mahabaleshwars"
