name: Maven with Custom Settings Path

on:
  workflow_dispatch:

jobs:
  build-with-custom-settings:
    name: Build with custom settings on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        distribution: [oracle, temurin, zulu, liberica, corretto, microsoft, semeru]
        java-version: [17,21]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK with custom settings path
        uses: aparnajyothi-y/setup-java@toolversions-regex-update
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          settings-path: ${{ github.workspace }}
      
      - name: Create project structure
        shell: bash
        run: |
          mkdir -p src/main/java/com/example/demo
          
      - name: Create Java class
        shell: bash
        run: |
          cat > src/main/java/com/example/demo/DemoApp.java << 'EOF'
          package com.example.demo;
          
          public class DemoApp {
              public String getMessage() {
                  return "Hello from Custom Settings Maven!";
              }
              
              public static void main(String[] args) {
                  System.out.println(new DemoApp().getMessage());
                  System.out.println("Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-07-20 16:35:24");
                  System.out.println("Current User's Login: mahabaleshwars");
              }
          }
          EOF
      
      - name: Create pom.xml with valid structure
        shell: bash
        run: |
          cat > pom.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
              <modelVersion>4.0.0</modelVersion>
              
              <groupId>com.example</groupId>
              <artifactId>demo-app</artifactId>
              <version>1.0.0-SNAPSHOT</version>
              <packaging>jar</packaging>
              
              <name>Demo App with Custom Settings</name>
              <description>Demo project for GitHub Actions Java custom settings</description>
              
              <properties>
                  <java.version>11</java.version>
                  <maven.compiler.source>${java.version}</maven.compiler.source>
                  <maven.compiler.target>${java.version}</maven.compiler.target>
                  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
              </properties>
              
              <!-- Use only one repository section -->
              <distributionManagement>
                  <repository>
                      <id>github</id>
                      <name>GitHub Packages</name>
                      <url>https://maven.pkg.github.com/${GITHUB_REPOSITORY}</url>
                  </repository>
              </distributionManagement>
              
              <build>
                  <plugins>
                      <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-compiler-plugin</artifactId>
                          <version>3.11.0</version>
                      </plugin>
                      <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-jar-plugin</artifactId>
                          <version>3.3.0</version>
                      </plugin>
                  </plugins>
              </build>
          </project>
          EOF
      
      # Handle settings.xml display differently for each OS
      - name: Show settings.xml (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "Settings.xml location: ${{ github.workspace }}/settings.xml"
          cat ${{ github.workspace }}/settings.xml || echo "Settings file not found"
          
          echo "Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-07-20 16:35:24"
          echo "Current User's Login: mahabaleshwars"
          
      - name: Show settings.xml (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          Write-Output "Settings.xml location: ${{ github.workspace }}\settings.xml"
          if (Test-Path "${{ github.workspace }}\settings.xml") {
            Get-Content "${{ github.workspace }}\settings.xml"
          } else {
            Write-Output "Settings file not found"
          }
          
          Write-Output "Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-07-20 16:35:24"
          Write-Output "Current User's Login: mahabaleshwars"
      
      - name: Build with Maven using custom settings
        run: mvn -B package --file pom.xml -s ${{ github.workspace }}/settings.xml
      
      - name: Run Maven effective-pom to verify settings
        run: mvn help:effective-pom -s ${{ github.workspace }}/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Report status
        run: |
          echo "Successfully built with custom settings path"
          echo "Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-07-20 16:35:24"
          echo "Current User's Login: mahabaleshwars"
