name: Maven Publishing to Central Repository

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-to-maven-central:
    name: Publish to Maven Central with ${{ matrix.distribution }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [temurin]
        java-version: [11]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      
      - name: Create project structure
        run: mkdir -p src/main/java/com/example/demo
      
      - name: Create Java class
        run: |
          cat > src/main/java/com/example/demo/DemoApp.java << 'EOF'
          package com.example.demo;
          
          public class DemoApp {
              public String getMessage() {
                  return "Hello from Maven Central Publisher!";
              }
              
              public static void main(String[] args) {
                  System.out.println(new DemoApp().getMessage());
                  System.out.println("Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-07-20 16:43:23");
                  System.out.println("Current User's Login: mahabaleshwars");
              }
          }
          EOF
      
      - name: Create pom.xml with correct structure
        run: |
          cat > pom.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
              <modelVersion>4.0.0</modelVersion>
              
              <groupId>io.github.mahabaleshwars</groupId>
              <artifactId>maven-central-demo</artifactId>
              <version>1.0.0-SNAPSHOT</version>
              <packaging>jar</packaging>
              
              <name>Maven Central Demo</name>
              <description>Demo project for publishing to Maven Central</description>
              <url>https://github.com/mahabaleshwars/Java-PR-Test</url>
              
              <licenses>
                  <license>
                      <name>MIT License</name>
                      <url>http://www.opensource.org/licenses/mit-license.php</url>
                  </license>
              </licenses>
              
              <developers>
                  <developer>
                      <id>mahabaleshwars</id>
                      <name>Developer Name</name>
                      <email>developer@example.com</email>
                      <organization>Example Organization</organization>
                      <organizationUrl>https://www.example.com</organizationUrl>
                  </developer>
              </developers>
              
              <scm>
                  <connection>scm:git:git://github.com/mahabaleshwars/Java-PR-Test.git</connection>
                  <developerConnection>scm:git:ssh://github.com:mahabaleshwars/Java-PR-Test.git</developerConnection>
                  <url>https://github.com/mahabaleshwars/Java-PR-Test/tree/main</url>
              </scm>
              
              <properties>
                  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                  <maven.compiler.source>11</maven.compiler.source>
                  <maven.compiler.target>11</maven.compiler.target>
              </properties>
              
              <!-- Correct structure with both snapshotRepository and repository -->
              <distributionManagement>
                  <snapshotRepository>
                      <id>ossrh</id>
                      <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
                  </snapshotRepository>
                  <repository>
                      <id>ossrh</id>
                      <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
                  </repository>
              </distributionManagement>
              
              <build>
                  <plugins>
                      <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-compiler-plugin</artifactId>
                          <version>3.11.0</version>
                      </plugin>
                      <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-source-plugin</artifactId>
                          <version>3.3.0</version>
                          <executions>
                              <execution>
                                  <id>attach-sources</id>
                                  <goals>
                                      <goal>jar-no-fork</goal>
                                  </goals>
                              </execution>
                          </executions>
                      </plugin>
                      <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-javadoc-plugin</artifactId>
                          <version>3.5.0</version>
                          <executions>
                              <execution>
                                  <id>attach-javadocs</id>
                                  <goals>
                                      <goal>jar</goal>
                                  </goals>
                              </execution>
                          </executions>
                      </plugin>
                      <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-gpg-plugin</artifactId>
                          <version>3.1.0</version>
                          <executions>
                              <execution>
                                  <id>sign-artifacts</id>
                                  <phase>verify</phase>
                                  <goals>
                                      <goal>sign</goal>
                                  </goals>
                                  <configuration>
                                      <gpgArguments>
                                          <arg>--pinentry-mode</arg>
                                          <arg>loopback</arg>
                                      </gpgArguments>
                                  </configuration>
                              </execution>
                          </executions>
                      </plugin>
                      <plugin>
                          <groupId>org.sonatype.plugins</groupId>
                          <artifactId>nexus-staging-maven-plugin</artifactId>
                          <version>1.6.13</version>
                          <extensions>true</extensions>
                          <configuration>
                              <serverId>ossrh</serverId>
                              <nexusUrl>https://s01.oss.sonatype.org/</nexusUrl>
                              <autoReleaseAfterClose>false</autoReleaseAfterClose>
                          </configuration>
                      </plugin>
                  </plugins>
              </build>
          </project>
          EOF
      
      - name: Check pom.xml structure
        run: |
          echo "Verifying pom.xml structure..."
          mvn help:effective-pom
      
      - name: Build with Maven
        run: mvn -B package
      
      - name: Deploy to Maven Central (Dry Run)
        run: mvn help:evaluate -Dexpression=project.version
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME || 'dummy-username' }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN || 'dummy-password' }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE || 'dummy-passphrase' }}
          
      - name: Report status
        run: |
          echo "Maven Central publishing workflow"
          echo "Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-07-20 16:43:23"
          echo "Current User's Login: mahabaleshwars"
