name: Maven Publishing to GitHub Packages

on:
  workflow_dispatch:

jobs:
  publish-to-github:
    name: Publish to GitHub Packages with ${{ matrix.distribution }} JDK ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution: [temurin, zulu, liberica]
        java-version: [11, 17]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: aparnajyothi-y/setup-java@toolversions-regex-update
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
          server-id: github

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
          KEY_ID=$(gpg --list-secret-keys --with-colons | grep '^sec' | cut -d':' -f5)
          echo "GPG_KEY_ID=$KEY_ID" >> $GITHUB_ENV
        env:
          GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

      - name: Configure GPG for Maven
        run: |
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo RELOADAGENT | gpg-connect-agent
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV

      - name: Build and Sign with Maven
        run: mvn -B deploy -Dgpg.passphrase="${{ secrets.MAVEN_GPG_PASSPHRASE }}" --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
