name: Publish to Multiple Registries

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  publish-to-multiple-registries:
    name: Publish to Multiple Registries
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # First publish to GitHub Packages
      - name: Set up JDK for GitHub Packages
        uses: aparnajyothi-y/setup-java@toolversions-regex-update
        with:
          distribution: temurin
          java-version: 11
          server-id: github
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      # Then publish to Maven Central
      - name: Set up JDK for Maven Central
        uses: aparnajyothi-y/setup-java@toolversions-regex-update
        with:
          distribution: temurin
          java-version: 11
          server-id: maven
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      
      - name: Publish to Maven Central
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      
      - name: Report status
        run: |
          echo "Successfully published to multiple registries"
          echo "Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-07-20 10:25:51"
          echo "Current User's Login: mahabaleshwars"
